### PR TITLE
Update SimCore to include recent features

### LINKED ISSUE #1234: Update LDMX-sw to include the new Kaon physics in SimCore and improved resimulation
See https://github.com/LDMX-Software/SimCore/pull/105, https://github.com/LDMX-Software/SimCore/issues/106, https://github.com/LDMX-Software/SimCore/pull/108, and https://github.com/LDMX-Software/SimCore/issues/107, https://github.com/LDMX-Software/SimCore/pull/109. 

These PRs introduce a couple of new and improved features for LDMX-sw that are relevant for upcoming analysis efforts. In particular 
- We let kaon properties be configurable at runtime (lifetimes and branching ratios) 
- Handle multiple input files during resim efforts 
- Increase the number of process types that can be assigned to sim particles so that less entries are marked as "Unknown" 

The only change that should make a difference is the last one, which I would expect to fail one figure in the SimObjects DQM. Everything else **should** be the same

### PR DESCRIPTION
**Pull request by EinarElen**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves #1234 

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] I ran my developments and the following shows that they are successful.
See PRs in SimCore

- [x] I attached any sub-module related changes to this PR.

### Related Sub-Module PRs
If you have developments in a submodule that you need to merge in along with these developments, please link those PRs here, otherwise just delete this section.
_Note_: You do not need to make a Sub-Module PR if your submodule developments are already on that repo's default branch.

- https://github.com/LDMX-Software/SimCore/pull/109 
- https://github.com/LDMX-Software/SimCore/pull/108
- https://github.com/LDMX-Software/SimCore/pull/105
- https://github.com/LDMX-Software/SimCore/pull/102
- https://github.com/LDMX-Software/SimCore/pull/101

Of these I expect one of the SimObjects DQM plots to fail (because primary particles will be counted as "Primary" rather than "Unknown"). W.r.t. the signal simulation, I leave it to @tomeichlersmith  to say if anything is expected to change

### CODE REVIEW

**Comment by EinarElen** [comment]
Right, so something was changed by all of this. I'm not sure why but TS and Hcal features seem to have changed but Ecal/other features have remained the same. 

[ecal_pn_fail.pdf](https://github.com/LDMX-Software/ldmx-sw/files/13448752/ecal_pn_fail.pdf)

**Comment by EinarElen** [comment]
The logs are different as well so something has changed w.r.t. the simulation 
```
Gold 
[ EcalProcessFilter ]: 10000 Brem photon produced 12 particle via biasWrapper(photonNuclear) process.
[ Simulator ] : Started 823126 events to produce 10000 events.
---- LDMXSW: Event processing complete  --------
PR 
[ EcalProcessFilter ]: 10000 Brem photon produced 36 particle via biasWrapper(photonNuclear) process.
[ Simulator ] : Started 824435 events to produce 10000 events.
---- LDMXSW: Event processing complete  --------

**Comment by EinarElen** [comment]
The first difference occurs at event 150
```
Gold 
[ EcalProcessFilter ]: 150 Brem photon produced 8 particle via biasWrapper(photonNuclear) process.
[ EcalProcessFilter ]: 150 Brem photon produced 10 particle via biasWrapper(photonNuclear) process.
PR 
[ EcalProcessFilter ]: 150 Brem photon produced 8 particle via biasWrapper(photonNuclear) process.
[ EcalProcessFilter ]: 150 Brem photon produced 9 particle via biasWrapper(photonNuclear) process.
```
So here something changed. As far as I can tell, this was the first time that there was a second PN attempt.

**Comment by EinarElen** [comment]
What fun, I can't reproduce either the gold or the PR log results on my machine....

**Comment by EinarElen** [comment]
On my machine with trunk vs PR branches for a very small ecal pn sample and using https://github.com/tomeichlersmith/root-diff/
```shell
LDMX_Events mismatched between files
== Branches with different content ==
EventHeader.timestamp_.fSec
EventHeader.timestamp_.fNanoSec
SimParticles_test.second.processType_
``` 

So this looks like what we would expect

**Comment by EinarElen** [comment]
Ok, I've confirmed that the difference comes from the introduction of the KaonPhysics, I will have to figure out what causes it.

**Comment by EinarElen** [comment]
I'm retracting my previous confirmation that the issue was caused by the kaon changes... There was an event seed mismatch between the two branches I was comparing so it doesn't tell us anything. The seed for the previous event however was the same (!?)

**Comment by EinarElen** [comment]
Found the culprit in a comment in a Geant4 header file:
```C++
// G4DecayTable.hh
// Insert a decay channel at proper position 
// (i.e. sorted by using branching ratio ) 
```

**Comment by EinarElen** [comment]
From the G4DecayTableMessenger, the accepted way to change the branching ratio of a process is 
```C++
void G4DecayTableMessenger::SetNewValue(G4UIcommand * command,G4String newValue)
{
    if (command == brCmd) {
      //Command   /particle/property/decay/br
      G4double  br = brCmd->GetNewDoubleValue(newValue);
      if( (br<0.0) || (br>1.0) ) { 
	G4cout << "Invalid brancing ratio. Command ignored." << G4endl;
      } else {
        currentChannel->SetBR(br);
      }
    }
  }
}
```

This doesn't change the location of the channel, so according to G4 we should be ok in doing this as well. To be sure, here is the algorithm used to pick decay channels 
```C++
while(true){
    G4double sumBR = 0.0;
    G4double r= G4UniformRand();
    // select decay channel
    for (auto channel : channels) {
      sumBR += channel->GetBR();
      if ( // Not allowed due to parent mass) { continue} 
      if (r < sumBR) return channel;
    }
  }
```

This should not depend on the order that the change is made. So we can use the _actual_ Geant4 positions safely.

**Comment by EinarElen** [comment]
Hey whaddya know only the expected to fail plots failed :)

**Comment by tomeichlersmith** [comment]
The only failing plot is the expected proceess type which makes me think we should probably add more bins since the bin max right now is 12

sim_dqm_sim_dqm_SimParticles process png

I am going to merge the SimCore patch and make a new SimCore release to be merged in.

**Review by tomeichlersmith — CHANGES_REQUESTED** [review]
Everything looks good here, I'm thankful the CI helped us find this very funky bug :100:

I have two house-keeping requests before I'm ready to merge.
1. Update SimCore to the v1.8.0 tag (I try to refer to the tag name in the commit message).
2. Update the SimParticle DQM to align with the increase in the number of process types. (maybe add the names to the bins as well?)

**Comment by EinarElen** [comment]
Updated process type histogram
Screenshot 2023-11-27 at 17 51 58

Checked that I didn't off-by-one the bin labels, there are 1k events and 1k in the "Primary" bin :)

**Comment by tomeichlersmith** [comment]
Were you running a special/nuclear config? I'm just surprised there are so many "unknowns"

**Comment by EinarElen** [comment]
It was a very soft kaon particle gun, so most of the unknown are ionization from hadrons

**Comment by EinarElen** [comment]
But that was what made me catch the pi-inelastic mapping being wrong :)

**Comment by EinarElen** [comment]
Ok, SimCore bumped!

**Review by tomeichlersmith — APPROVED** [review]

**Pull request merged**
