### PR TITLE
Iss521 - Allows the use of GPS

### LINKED ISSUE #521: Enable the use of GPS

### PR DESCRIPTION
**Pull request by omar-moreno**
This resolves #521.

### CODE REVIEW

**Comment by nhanvtran** [comment]
no problem with the merge, just a question for @omar-moreno 
could GPS work with LHE generation too?

**Comment by omar-moreno** [comment]
I haven't tested it, but I don't see any reason why it shouldn't. I'm happy
to open a new issue and test if it's needed.

**Comment by omar-moreno** [comment]
Sorry for the forced merge.  I needed some changes in the master for other
work I'm doing.

**Comment by nhanvtran** [comment]
no worries at all -- review went past statute of limitations 😄.  i'll play around with GPS + another generator

**Pull request merged**
