### PR TITLE
Sim core iss86

### LINKED ISSUE #1161: Event topology based PN filters + Alternative PN models
**Is your feature request related to a problem? Please describe.**
The main work here is over in https://github.com/LDMX-Software/SimCore/pull/88 and the corresponding issue https://github.com/LDMX-Software/SimCore/issues/86. However, in order for some of the models in there to be useful, you want to have some filters that veto events that don't have the kind of final state that you are interested in. This can happen for example if you have a PN reaction with a nucleus where you don't apply your model. 

To make adding such filters straight forward a generic filter ABC for looking at a PN event and based on the secondaries either accept or reject. I've included two such filters for the nothing hard/single neutron case. There isn't a need for a filter corresponding to the https://github.com/LDMX-Software/SimCore/blob/3aea21f15567975c86ee267753cf01749f6884f0/include/SimCore/PhotoNuclearModels/BertiniAtLeastNProductsModel.h model since the current PN products filter does this.

Chronologically, this should come after #1135 and #1160.

### PR DESCRIPTION
**Pull request by EinarElen**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves #1161. Most of the details are over in SimCore, but this does add a new filter category that lets you veto events where you had a PN reaction but it didn't produce a final state that you are interested in. This includes two such filters, but adding new ones is trivial and shouldn't really require more code than e.q. 
```C++
bool SomeFilter::rejectEvent(
    const std::vector<G4Track*>& secondaries) const {
  for (const auto& secondary : secondaries) {
    // Get the PDG ID of the track
    const auto pdgID{
        std::abs(secondary->GetParticleDefinition()->GetPDGEncoding())};
    if (skipCountingParticle(pdgID)) {
      continue;
    }
    auto energy{secondary->GetKineticEnergy()};
   // Perform some bookkeeping 
  }
  // Decide on or not to reject the event
  return some_veto_condition;
}
```

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] I ran my developments and the following shows that they are successful.
See the SimCore PR
- [x] I attached any sub-module related changes to this PR.

### Related Sub-Module PRs
If you have developments in a submodule that you need to merge in along with these developments, please link those PRs here, otherwise just delete this section.
_Note_: You do not need to make a Sub-Module PR if your submodule developments are already on that repo's default branch.

- https://github.com/LDMX-Software/SimCore/pull/88

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
The "conflicts" are due to the commits that were merged into `trunk` not via rebase and are here. You could try `git rebase -i` and remove the commits already merged, or just create a new branch.
```
git checkout trunk
git pull
git branch -D SimCore-iss86 # delete local copy of this branch
git checkout -b SimCore-iss86 # create new branch off trunk with same name
# make desired changes, probably updating SimCore
cd SimCore
git checkout trunk
git pull
cd ..
git add SimCore
git commit -m "update SimCore with new PN model infrastructure"
# forcefully push your new local branch to this one, setting this one as its upstream
git push -fu origin trunk
```

**Comment by tomeichlersmith** [comment]
*Bad news*: The PR validation was run _before_ the updated gold histograms were merged into trunk so they do not faithfully check against the new histograms.

*Good news*: It looks like the exact same histograms failed as in PR #1160 which would imply that this PR does not change the PN DQM (which is expected and what we would want).

I am going to ask for the workflow to be "rerun" - although I fear that it will use the old trunk commit in order to do a "perfect" rerun.

**Comment by EinarElen** [comment]
If we need to change something to trigger a rerun, we could add Lenes suggested change for the default TS collection name (I'll test it locally first of course)

**Review by tomeichlersmith — APPROVED** [review]
Good work, this looks great :)

For my future reference: I confirmed that SimCore is on tag v1.5.0

**Review by bryngemark — APPROVED** [review]

**Pull request merged**
