### PR TITLE
Patch up GitHub actions

### LINKED ISSUE #838: GitHub actions don't pull down submodules
**Describe the bug**
Actions don't pull down submodules which breaks them.

**Expected behavior**
We want the action to basically `clone --recursive` so that we can do tests and build the docker production image.

### PR DESCRIPTION
**Pull request by tomeichlersmith**
This resolves #838 , thank you @GeoffreyMullier for finding the necessary GitHub actiont to pull down submodules.

The testing action now works as expected and the production image will be generated on each push to master as well as on releases. The production image will be tag with the commit sha, any branch identifiers (for the release tag number), and `latest`. This might be overkill, but we can remove those options later if we want to.

@omar-moreno You need to add your docker username and password to the GitHub secrets for the repository in order to the generated production image to be pushed to docker hub. Your username should be `DOCKER_USERNAME` and your password should be `DOCKER_PASSWORD`.

Technically, I could add mine, but I don't have access to the Settings tab for this repo. Also technically we could link this repo through docker hub, but then we can't add specialized tags based off of the releases.

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
Some of the tests got broken from the updates to Process. Need to do those updates before merge.

**Comment by omar-moreno** [comment]
Ready? :)

**Comment by tomeichlersmith** [comment]
I'm so close, just want to rebase onto master to double check that logging doesn't break the tests.

**Comment by tomeichlersmith** [comment]
Have you added your docker username/password to the secrets?

**Comment by omar-moreno** [comment]
Yes, they are in.

**Comment by tomeichlersmith** [comment]
@omar-moreno ready!

**Pull request merged**
