### PR TITLE
Iss850 - Update to target based CMake.

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by omar-moreno** [comment]
@tomeichlersmith Yes to both.

**Comment by tomeichlersmith** [comment]
This branch is still pointing at a reference in the submodules that doesn't have your changes, that is what is throwing the `cmake` error:
```
cmake version 3.18.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
-- The CXX compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Install directory set to /home/runner/work/ldmx-sw/ldmx-sw/install
-- Python install directory set to /home/runner/work/ldmx-sw/ldmx-sw/install/python/LDMX
-- Setting build type to 'Release' as none was specified.
-- Building all modules.
-- Build the Framework.
CMake Error at Framework/CMakeLists.txt:3 (module):
  Unknown CMake command "module".


-- Configuring incomplete, errors occurred!
See also "/home/runner/work/ldmx-sw/ldmx-sw/build/CMakeFiles/CMakeOutput.log".
##[error]Process completed with exit code 1.
```
You need to update the submodule references by doing:
```
git checkout iss850
cd Ecal
git checkout <cmake-changes-branch>
cd ../Framework
git checkout <cmake-changes-branch>
cd ../SimCore
git checkout <cmake-changes-branch>
cd ..
git add *
git commit -m "update submodule references"
```

**Comment by omar-moreno** [comment]
I know.  I wasn't going to make that update until things are merged into
other submodules. However, I did notice the cmake version error which is
independent of this.

**Comment by tomeichlersmith** [comment]
Whoops! Sorry, I didn't see your message

**Comment by tomeichlersmith** [comment]
Well I guess my mistake revealed another bug, in the previous cmake stuff, I added the location of ONNX in the container to the default search list so that cmake could find it easily when people are using the container:
```
# add the path in the docker container here
set(_ONNXRUNTIME_SEARCHES "/deps/onnxruntime")
```
Is something similar possible with the updated cmake?

**Comment by omar-moreno** [comment]
This is the kind of thing I want to test now. Now that cmake is updated, I
can take care of the rest of these issues.

**Comment by omar-moreno** [comment]
> Well I guess my mistake revealed another bug, in the previous cmake stuff, I added the location of ONNX in the container to the default search list so that cmake could find it easily when people are using the container:
> 
> ```
> # add the path in the docker container here
> set(_ONNXRUNTIME_SEARCHES "/deps/onnxruntime")
> ```
> 
> Is something similar possible with the updated cmake? Got it, can add "/deps/" to the list of search paths:
> 
> ```
> find_path(onnxruntime_include_dir
>               NAMES onnxruntime_cxx_api.h
>               PATHS ${ONNXRuntime_INCLUDE_DIRS} "/deps/"
>               PATH_SUFFIXES onnxruntime
>     )
> ```

Something I should have mentioned, the ONNXRuntime binaries are now downloaded automatically into an external directory within build.  I created a find module which automatically detects the location and and creates a target.  So there shouldn't be a need to add "/deps/".

**Comment by omar-moreno** [comment]
Also, the Catch2 header is also now downloaded automatically and the executable built on the fly.  So there is no need to include it as a dependency.

**Pull request merged**
