### PR TITLE
Iss1063

### PR DESCRIPTION
**Pull request by EinarElen**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves parts **(but not all!)** of https://github.com/LDMX-Software/ldmx-sw/issues/1063 

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] I ran my developments and the following shows that they are successful.
I've tested the config file in the issue with both `ldmx-hcal-prototype-v1.0`, `ldmx-hcal-prototype-v1.0`, and `ldmx-det-v13` and checked that
- the position map changes looked right (using the `printPositionMap` debug function in the HcalGeometry setup. 
- that runs with a particle gun placed to the right gets both SimHit and RecHit position distributions shifted to the right 
- The HcalRecProducer doesn't crash because the HcalID's from the SimHits matches the geometry 

- [x] I attached any sub-module related changes to this PR.

### Related Sub-Module PRs
If you have developments in a submodule that you need to merge in along with these developments, please link those PRs here, otherwise just delete this section.
- https://github.com/LDMX-Software/SimCore/pull/64 
-  https://github.com/LDMX-Software/Hcal/pull/48

### CODE REVIEW

**Review by tomeichlersmith — APPROVED** [review]
This PR is a _mega_ PR that also updates Hcal and SimCore to their initial release commits which contain a variety of bug fixes and enhancements developed via testbeam. I am going to trigger a re-run of the PR validation test to make sure that our basic simulation and basic reconstruction have not been broken, but if that passes, I'll be ready to merge.

**Comment by cmantill** [comment]
@EinarElen would this be a good place to integrate your old commit on the detector description string? https://github.com/LDMX-Software/ldmx-sw/commit/9f2e2e6d4a48e6f3111936f445c9e1320719da3f

**Comment by EinarElen** [comment]
Yeah that would make sense, would resolve https://github.com/LDMX-Software/ldmx-sw/issues/1047

**Comment by tomeichlersmith** [comment]
I think that makes sense, go ahead and add that commit to this branch!

**Review by cmantill — APPROVED** [review]
looks good, @tomeichlersmith can you trigger the long checks?

**Comment by tomeichlersmith** [comment]
I already did and they are [almost complete](https://github.com/LDMX-Software/ldmx-sw/runs/7430769716?check_suite_focus=true) - they don't test the string printout of the HcalGeometry, so that commit doesn't need to be included.

**Pull request merged**
