### PR TITLE
SimCore submodule at v1.8.3 (LHE reader generalization)

### LINKED ISSUE #1270: Support LHE v3.0
**Is your feature request related to a problem? Please describe.**

Both the NLO MadGraph LHE output and default MadGraph 3.5.3 LHE output are formatted with the lhef3.0 formatting. A typical block looks like
```
<event>
 6      1 +1.2560691e-08 1.79574400e+03 7.81860800e-03 1.15969700e-01
        1 -1    0    0  501    0 +0.0000000000e+00 +0.0000000000e+00 +1.7616005291e+03 1.7616005291e+03 0.0000000000e+00 0.0000e+00 1.0000e+00
       11 -1    0    0    0    0 -0.0000000000e+00 -0.0000000000e+00 -1.0000000000e+03 1.0000000000e+03 0.0000000000e+00 0.0000e+00 -1.0000e+00
        1  1    1    2  501    0 -8.3240135047e+01 +1.6927747814e+02 +5.6965842916e+02 6.0007875367e+02 0.0000000000e+00 0.0000e+00 1.0000e+00
       11  1    1    2    0    0 +2.7632667555e+02 -1.4043744658e+02 +2.1270782660e+02 3.7593048230e+02 0.0000000000e+00 0.0000e+00 -1.0000e+00
  9000003  1    1    2    0    0 +1.1820400163e+02 -6.1600025824e+02 +1.1629746329e+02 8.7781695365e+02 6.0300000000e+02 0.0000e+00 -1.0000e+00
 -9000003  1    1    2    0    0 -3.1129054213e+02 +5.8716022669e+02 -1.3706318994e+02 9.0777433950e+02 6.0300000000e+02 0.0000e+00 -1.0000e+00
<mgrwt>
<rscale>  0 0.18863665E+03</rscale>
<asrwt>0</asrwt>
<pdfrwt beam="1">  1        1 0.27101546E+00 0.18863665E+03</pdfrwt>
<pdfrwt beam="2">  1       11 0.10000000E+01 0.17957444E+04</pdfrwt>
<totfact> 0.55095125E+00</totfact>
</mgrwt>
</event>
``` 
i.e. a change from v2.0 is that there is a block of `<mgrwt>`.

This leads to issues with the current implementation of the LHE reader, as it expects everything before `</event>` to be part of the event.

**Describe the solution you'd like**

Make the LHEReader able to read v3.0 files.

**Describe alternatives you've considered**

Forcing the MadGraph to output in v2.0, but I think it's better to just add the functionality to read v3.0 in LDMX

### PR DESCRIPTION
**Pull request by tvami**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
This resolves https://github.com/LDMX-Software/ldmx-sw/issues/1270

To ensure backward compatibility I ran on https://github.com/LDMX-Software/ldmx-sw/blob/trunk/.github/validation_samples/ecal_pn/config.py
--> runs fine

Then I ran on an LHE which has the v3 format, and the original error of the "Wrong number of tokens in LHE particle record." is gone.

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.
- [x] I attached any sub-module related changes to this PR.

### Related Sub-Module PRs
https://github.com/LDMX-Software/SimCore/pull/114

### CODE REVIEW

**Review by tomeichlersmith — CHANGES_REQUESTED** [review]
Awesome :raised_hands: thank you for going through the double-PR rigamarole.[^1]

The general strategy I have is to keep submodules on tagged releases, so the procedure [described online](https://ldmx-software.github.io/prs.html#merging-a-pr) is

1. Merge the submodule PR
2. Create a submodule release for that fix
3. Double check (update if need be) that the commit reference here is that tag
4. Merge this PR

I'm now realizing that we may have too strict requirements on review to make this process functional without admin intervention (since I think releases require admin access to that git repo). Maybe a side project here could be asking you to see what permissions you have in SimCore: can you merge your PR after my one review? could you make a new release?

Anyways, the changes I'm requesting are to follow the above procedure. Ideally, since this PR only consists of updating the submodule, this PR would just be one commit with the message `SimCore on <version>` or something like that.

[^1]: Any ideas on how to make it smoother/easier to contribute to submodules welcome.

**Comment by tvami** [comment]
>  asking you to see what permissions you have in SimCore: can you merge your PR after my one review? 

It needs two reviews, I could give it a try and add my own review :P and see if that works.

> this PR would just be one commit with the message `SimCore on <version>`

I could `rebase`/`reword` the commit on this PR, no problem. 

> Any ideas on how to make it smoother/easier to contribute to submodules welcome. 

My understanding is that the submodules were motivated because there was a lot of development happening in paralell, now that the software is in a more stable part, I'm wondering if this still makes sense or we should just merge everything into one big module (like CMSSW). [also this is beyond this PR, maybe we should have a separate issue about this (or just kill my suggestion now and that also resolves it hahaha)]

**Review by tomeichlersmith — CHANGES_REQUESTED** [review]
Thank you for re-wording the commit! Unfortunately, our submodule-based workflow is even more complicated :face_exhaling: 

SimCore is not on the v1.8.3 tag (although it is on a commit with identical source code).
```
tom@appa:~/code/ldmx/ldmx-sw$ git branch -vv
  1232-use-denv-in-ldmx-env 312a58d4 [origin/1232-use-denv-in-ldmx-env: behind 13] auto-install denv so its so light, add printouts to transition
* iss1270                   539e0446 [origin/iss1270] SimCore submodule at v1.8.3 (LHE reader generalization)
  patch-module-selection    18059af4 only build event library corresponding to requested modules
  trunk                     39fc257c [origin/trunk: behind 16] Bump ldmx/dev from 4.2.0 to 4.2.1
tom@appa:~/code/ldmx/ldmx-sw$ git -C SimCore describe --tags
v1.8.2-1-g11b0e48
tom@appa:~/code/ldmx/ldmx-sw$ git -C SimCore diff v1.8.3
tom@appa:~/code/ldmx/ldmx-sw$ 
```
This reason for this is because a new commit was created when merging the submodule PR:
```
tom@appa:~/code/ldmx/ldmx-sw/SimCore$ git log --graph --oneline --all
* 191f2ec (tag: v1.8.3, origin/trunk, origin/HEAD) Generalize LHEReader so it can read LHE v3.0 input as well
| * 11b0e48 (HEAD, origin/iss1270) Generalize LHEReader so it can read LHE v3.0 input as well
|/  
* c8a30c1 (tag: v1.8.2) enable all .py files in test to be tests
```
The solution for this is to intentionally checkout the tag created by the SimCore release.
```
tom@appa:~/code/ldmx/ldmx-sw$ git -C SimCore fetch --tags && git -C SimCore checkout v1.8.3
Previous HEAD position was 11b0e48 Generalize LHEReader so it can read LHE v3.0 input as well
HEAD is now at 191f2ec Generalize LHEReader so it can read LHE v3.0 input as well
tom@appa:~/code/ldmx/ldmx-sw$ git -C SimCore fetch --tags && git -C SimCore checkout v1.8.3
Previous HEAD position was 11b0e48 Generalize LHEReader so it can read LHE v3.0 input as well
HEAD is now at 191f2ec Generalize LHEReader so it can read LHE v3.0 input as well
tom@appa:~/code/ldmx/ldmx-sw$ git -C SimCore describe --tags
v1.8.3
```
Then you could re-make the commit for this PR:
```
git add SimCore
git commit --amend --no-edit
```
(`--no-edit` because I like the wording it currently has)

**Review by tomeichlersmith — APPROVED** [review]
Looks good, updating SimCore to the new release tag:
```
tom@appa:~/code/ldmx/ldmx-sw$ git submodule status
 4056cf8684bd6eea0e13e4ab3e24958ccf8124e3 Conditions (v0.1.0)
 c92f48575ab1e4ea90c1b14c2c414727383a9ce6 Ecal (v0.2.6)
 1eb1fba1bfe8a88a29947524e14fd9ed2dd89e6a Framework (v1.4.2)
 ac43c59c00adb1fad16aa6b7a63b0386ef8ebe43 Hcal (v0.3.6)
 08e5aa5c72fb82fe3ce123fff0c6483610c10ba6 MagFieldMap (v0.1.0)
 191f2eccfefb20f293f9c2e8ab5e89ec3da1d9aa SimCore (v1.8.3)
 a1a9ec8e51cf9c22e8be788e6d7fbf7235239902 Tracking (v1.2.1)
 cb60589597edea854031594e25ead4a37fc1c829 TrigScint (remotes/origin/iss53-4-gcb60589)
 c5731f01be27233c166fc7ff416677a0d95f4b87 Trigger (v0.1.0)
 f3a9248f28597ccdc2542e142d06f4fb31dd92f7 cmake (v0.4.0)
 df83fbf22cfff76b875c13d324baf584c74e96d0 docs/doxygen.conf/doxygen-awesome-css (v2.2.1)
```

**Pull request merged**
