### PR TITLE
Iss882 - Install external packages in CMAKE_INSTALL_PREFIX

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by omar-moreno** [comment]
Resolves #882

**Comment by omar-moreno** [comment]
> Two issues:
> 
>     1. I wrote a short cmake code that automatically generates a helpful python function/module. You can add it to the python stuff in the setup_library macro:
> 
> 
> ```
> # write an __init__ file for this python module (if any python scripts are installed)
> file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py 
>     "\"\"\"Python module to configure the LDMX module ${setup_library_name}\"\"\"")
> install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py 
>         DESTINATION ${setup_library_python_install_path}/${setup_library_name})
> 
This is there. 

> # write an include file for this module
> file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/include.py
>     "\"\"\"Include this module\"\"\"\ndef library() :\n\ \ \ \ \"\"\"Attach the name of ${setup_library_name} library to the process\"\"\"\n\ \ \ \ from LDMX.Framework.ldmxcfg import Process\n\ \ \ \ Process.addLibrary('${CMAKE_INSTALL_PREFIX}/lib/lib${setup_library_name}.so')")
> install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/include.py 
>         DESTINATION ${setup_library_python_install_path}/${setup_library_name})
> ```
> 
I excluded this part because it's specific to LDMX.  Let me see if I can drop it in somewhere in a more generic way.

>     1. I am receiving a linking error when I try to run `fire` in the container. This is coming from Geant4, and I remember something similar happening before. I'll see if I can dig up the fix.
>        I think it has something to do with the fact that the `Geant4::Interface` target does not set a path to the libraries. I'm not sure how to do this, but it should be fairly easy? Before we got the Geant4 library list using `include(${Geant4_USE_FILE})` and then `Geant4_LIBRARIES` listed all of the Geant4 libraries at the Geant4 install location.
>        It looks like adding the following line to the `set_target_properties` call inside `setup_geant4_target` macro would do it:
> 
I'll look into this.  This, again, is likely Ubuntu specific because I haven't had issues on CentOS7, Rhel6 and OpenSuse Leap. 

> 
> ```
> INTERFACE_LINK_LIBRARIES "${Geant4_LIBRARIES}"
> ```

**Comment by tomeichlersmith** [comment]
Let me know if you need help setting up the container, I think it will be faster if you do that and patch it up from there.

**Comment by omar-moreno** [comment]
Sounds good.

**Comment by tomeichlersmith** [comment]
Got it. Here are the changes I made so that it compiles and runs:

## cmake
Add Geant4 Libraries to Interface target.
```
#In BuildMacros.cmake
         # Set the target properties
         SET_TARGET_PROPERTIES(Geant4::Interface
             PROPERTIES
+            INTERFACE_LINK_LIBRARIES "${Geant4_LIBRARIES}"
             INTERFACE_COMPILE_OPTIONS "${Geant4_Flags}"
             INTERFACE_COMPILE_DEFINITIONS "${LDMX_Geant4_DEFINITIONS}"
             INTERFACE_INCLUDE_DIRECTORIES "${Geant4_INCLUDE_DIRS}"
```
The mag field map installation depended on the location of the script relative to the MagFieldMap directory.
```
#In InstallMagFieldMap.cmake
 file(MAKE_DIRECTORY ${CMAKE_INSTALL_PREFIX}/data/fieldmap)
-file(GLOB fieldmap_files ${CMAKE_CURRENT_LIST_DIR}/../../MagFieldMap/*.tar.gz)
+file(GLOB fieldmap_files ${CMAKE_CURRENT_LIST_DIR}/../MagFieldMap/*.tar.gz)
 foreach(fieldmap_file ${fieldmap_files})
```
Make sure the `__init__.py` file has a numpy docstring so that sphinx-apidoc will document it.
```
#In BuildMacros.cmake
-        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py "") 
-        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py 
+        # write an __init__ file for this python module (if any python scripts are installed)
+        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py
+            "\"\"\"Python module to configure the DARK module ${setup_library_name}\"\"\"")
+        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py
+                DESTINATION ${setup_library_python_install_path}/${setup_library_name})
```
Write a python module to include the dynamic library in the process. I know you said that this is LDMX specific, but I don't think so. If anyone is using Framework, this is helpful for writing modules that are run through Framework. 
```
#In BuildMacros.cmake again
+        # write an include file for this module
+        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/include.py
+            "\"\"\"Include this module\"\"\"\ndef library() :\n\ \ \ \ \"\"\"Attach the name of ${setup_library_name} library to the process\"\"\"\n\ \ \ \ from LDMX.Framework.ldmxcfg import Process\n\ \ \ \ Process.addLibrary('${CMAKE_INSTALL_PREFIX}/lib/lib${setup_library_name}.so')")
+        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/include.py
```
If you want to change the reference `LDMX` in the python function, we could define the python root module name as a cmake parameter (e.g. PYTHON_ROOT_MODULE_NAME) and then we would replace all occurrences of `LDMX` with `${PYTHON_ROOT_MODULE_NAME}`.

## SimCore
Some parts of SimCore use ROOT physics and math libraries.
```
 # in CmakeLists.txt
+# Search and configure ROOT
+find_package(ROOT 6.16 CONFIG REQUIRED)
+
 # Configure Geant4
 setup_geant4_target()
 
 # Setup the library 
 setup_library(name SimCore 
-              dependencies Geant4::Interface DARK::Framework DARK::DetDescr
+              dependencies Geant4::Interface ROOT::Physics ROOT::MathCore DARK::Framework DARK::DetDescr
               python_install_path ${PYTHON_INSTALL_PREFIX}
 )
```

**Comment by omar-moreno** [comment]
> Got it. Here are the changes I made so that it compiles and runs:
> ## cmake
> 
> Add Geant4 Libraries to Interface target.
> 
> ```
> #In BuildMacros.cmake
>          # Set the target properties
>          SET_TARGET_PROPERTIES(Geant4::Interface
>              PROPERTIES
> +            INTERFACE_LINK_LIBRARIES "${Geant4_LIBRARIES}"
>              INTERFACE_COMPILE_OPTIONS "${Geant4_Flags}"
>              INTERFACE_COMPILE_DEFINITIONS "${LDMX_Geant4_DEFINITIONS}"
>              INTERFACE_INCLUDE_DIRECTORIES "${Geant4_INCLUDE_DIRS}"
> ```
I've added the Geant4 libraries.
> 
> The mag field map installation depended on the location of the script relative to the MagFieldMap directory.
> 
> ```
> #In InstallMagFieldMap.cmake
>  file(MAKE_DIRECTORY ${CMAKE_INSTALL_PREFIX}/data/fieldmap)
> -file(GLOB fieldmap_files ${CMAKE_CURRENT_LIST_DIR}/../../MagFieldMap/*.tar.gz)
> +file(GLOB fieldmap_files ${CMAKE_CURRENT_LIST_DIR}/../MagFieldMap/*.tar.gz)
>  foreach(fieldmap_file ${fieldmap_files})
> ```
> 
This code is now gone.  I'm hadn't realized it had relatives paths coded in, but that's just asking for issues. The MagFieldMap module now has it's own CMakeLists.txt. 

> Make sure the `__init__.py` file has a numpy docstring so that sphinx-apidoc will document it.
> 
> ```
> #In BuildMacros.cmake
> -        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py "") 
> -        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py 
> +        # write an __init__ file for this python module (if any python scripts are installed)
> +        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py
> +            "\"\"\"Python module to configure the LDMX module ${setup_library_name}\"\"\"")
> +        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/__init__.py
> +                DESTINATION ${setup_library_python_install_path}/${setup_library_name})
> ```
> 
I actually want to remove this completely. Starting with python 3.3, __init__.py is no longer needed to declare a package.  In fact, the guideline now seems to be to not use this unless you will be executing code in it.  

> Write a python module to include the dynamic library in the process. I know you said that this is LDMX specific, but I don't think so. If anyone is using Framework, this is helpful for writing modules that are run through Framework.
> 
> ```
> #In BuildMacros.cmake again
> +        # write an include file for this module
> +        file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/python/include.py
> +            "\"\"\"Include this module\"\"\"\ndef library() :\n\ \ \ \ \"\"\"Attach the name of ${setup_library_name} library to the process\"\"\"\n\ \ \ \ from LDMX.Framework.ldmxcfg import Process\n\ \ \ \ Process.addLibrary('${CMAKE_INSTALL_PREFIX}/lib/lib${setup_library_name}.so')")
> +        install(FILES ${CMAKE_CURRENT_BINARY_DIR}/python/include.py
> ```
> 
> If you want to change the reference `LDMX` in the python function, we could define the python root module name as a cmake parameter (e.g. PYTHON_ROOT_MODULE_NAME) and then we would replace all occurrences of `LDMX` with `${PYTHON_ROOT_MODULE_NAME}`.
> ## Framework
> 

> Some modules use ROOT physics and math libraries and linking through Framework is their only connection to ROOT. We could have them each individual import ROOT on their own, but I think that is overkill.
> 
> ```
>  # in CMakeLists.txt
> -              dependencies Python3::Python ROOT::Hist ROOT::TreePlayer 
> +              dependencies Python3::Python ROOT::Hist ROOT::TreePlayer ROOT::MathCore ROOT::Physics
> ```

I've added this here for now but if other packages are pulling in those dependencies through Framework, they should be added to them as well.

**Comment by omar-moreno** [comment]
Given that all include.py files will be removed, I'm going to merge this in.

**Comment by omar-moreno** [comment]
Sphinx is still failing to generate the documentation, but that will be resolved by another issue.

**Pull request merged**
