### PR TITLE
Python config cleanup and enable single-file standalone processors

### LINKED ISSUE #1308: Compiling stand-alone C++ Processors from Python Config
While writing https://ldmx-software.github.io/analysis/ldmx-sw.html I realized that it is relatively easy to write a stand-alone, single-file analyzer (or producer for that matter) due to our library loading mechanism. I also realized that, since the library loading happens _after_ the python config has been fully run, we can do the compilation of the stand-alone single-file processor within the python config.

For this to work, I currently have to write my own `class` that mimics the `LDMX.Framework.ldmxcfg.EventProcessor` class but just omits the `addModule` within the constructor. (This is done in the linked documentation.)

https://github.com/LDMX-Software/ldmx-sw/blob/11d6a8e89250b357885602075c88b423dc04cdeb/Framework/python/ldmxcfg.py.in#L34-L39

If we updated `EventProcessor` to be something like
```python

from pathlib import Path
import subprocess

class EventProcessor:
    def __init__(self, instanceName, className, library):
        self.instanceName = class_name
        self.className = class_name
        self.histograms = []

        if library.endswith('.so'):
            # assume user is passing a filepath to load
            Process.addLibrary(library)
        else:
            # assume user has just passed the name of the module the class is compiled into
            Process.addModule(library)

    def from_file(fp, class_name = None, instance_name = None, **config_kwargs):
        if not isinstance(fp, Path):
            fp = Path(fp)
        if not fp.is_file():
            raise ValueError(f'{fp} is not accessible.')
        
        src = fp.resolve()
        if class_name is None:
            # assume class name is name of file if not provided
            class_name = fp.stem
        if instance_name is None:
            # use class name for instance name if not provided
            instance_name = class_name
        
        lib = src.parent / f'lib{src.stem}.so'
        if not lib.is_file() or src.stat().st_mtime > lib.stat().st_mtime:
            print('Analyzer source is newer than the library, recompiling...') # could make this optional
            import subprocess
            subprocess.run([
              'g++', '-fPIC', '-shared', '-o', str(lib.resolve()),
              '-lFramework', '-I/usr/local/include/root', str(src.resolve())
            ], check=True)

        instance = EventProcessor(instance_name, class_name, str(lib.resolve()))
        for cfg_name, cfg_val in config_kwargs:
            setattr(instance, cfg_name, cfg_val)
        return instance
```
Then we could have configs loading single-file processors. For example
```cpp
// in MyAnalyzer.cxx
#include "Framework/EventProcessor.h"

#include "Ecal/Event/EcalHit.h"

class MyAnalyzer : public framework::Analyzer {
 public:
  MyAnalyzer(const std::string& name, framework::Process& p)
    : framework::Analyzer(name, p) {}
  ~MyAnalyzer() = default;
  void onProcessStart() final;
  void analyze(const framework::Event& event) final;
};

void MyAnalyzer::onProcessStart() {
  // this is where we will define the histograms we want to fill
}

void MyAnalyzer::analyze(const framework::Event& event) {
  // this is where we will fill the histograms
}

DECLARE_ANALYZER(MyAnalyzer);
```
could be run with
```python
// config.py
from LDMX.Framework import ldmxcfg
p.sequence = [ ldmxcfg.Analyzer.from_file('MyAnalyzer.cxx') ]
p.inputFiles = [ 'events.root' ]
p.histogramFile = 'hist.root'
```

### LINKED ISSUE #1309: Remove CMake configuration of Python modules
The CMake configuration of the parent Python module originated from a time when we were expecting the more stable modules (like Framework and SimCore) to be adopted by other experiments and thus the parent python module might change to something other than `LDMX`. Now, it is just clutter that we can undo in order to avoid further confusion down the road.

We can remove

https://github.com/LDMX-Software/ldmx-sw/blob/11d6a8e89250b357885602075c88b423dc04cdeb/CMakeLists.txt#L43-L44

and drop its usage in all the submodule `CMakeLists.txt`.

This then means we can change the `.py.in` Python files into `.py` by replacing `@PYTHON_PACKAGE_NAME@` with `LDMX` and update the following to just look for `.py` and use the `COPY_ONLY` option of `configure_file`.

https://github.com/LDMX-Software/ldmx-sw/blob/11d6a8e89250b357885602075c88b423dc04cdeb/cmake/BuildMacros.cmake#L168-L205

### PR DESCRIPTION
**Pull request by tomeichlersmith**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?

This resolves #1308 and #1309 . Resolving #1309 was simply a chore, dropping the `.in` suffixes on some of the python files allows for them to be better syntax highlighted in our text editors and on GitHub. These files are still being configured by CMake so when building happens allowing for them to access build information (for example the install prefix), but since we can follow CMake's [configure_file](https://cmake.org/cmake/help/latest/command/configure_file.html) variable-replacement syntax (using `${var}` or `@var@`) _and_ maintain Python syntax (wrapping the var in quotes) it is a win-win. I also removed some relic examples that were not being maintained and were mistakenly carried through the de-submodule transition.

#1308 was resolved by pretty much following the outline I found in that issue and modifying it slightly to support both system installs of ldmx-sw (like is found in production images) and non-system installs (like is found when compiling ldmx-sw locally with a dev image). **Note**: there is a limitation to this file. We only link the `Framework` library (and thus the event dictionary as well) to the single-file compiled library. I think this makes sense. If you want to use non-event-object stuff from other modules, that is a good sign to just put the processor in that module (or some other module within ldmx-sw and its more complete compilation infrastructure).

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

The default tests will check the normal way of running ldmx-sw that removing `PYTHON_PACKAGE_NAME` could affect. Below, I've copied the evidence that the new `from_file` function is operating as expected. Since it contains a lot of lines, I am putting it withing a collapsing HTML section so you only need to see it when you want to. The TLDR is that I can run an analyzer from a passed source file, the library for that analyzer is only compiled when it doesn't exist or the analyzer source code has changed.

<details>
  <summary>Evidence that from_file is Working</summary>

I have two files starting in the working directory.

**MyAnalyzer.cxx**
```cpp
// in MyAnalyzer.cxx
#include "Framework/EventProcessor.h"
// not used but want to make sure includes from other modules is working
#include "Ecal/Event/EcalHit.h"

class MyAnalyzer : public framework::Analyzer {
 public:
  MyAnalyzer(const std::string& name, framework::Process& p)
    : framework::Analyzer(name, p) {}
  ~MyAnalyzer() = default;
  void analyze(const framework::Event& event) final;
};

void MyAnalyzer::analyze(const framework::Event& event) {
  std::cout << event.getEventNumber() << " Hello from MyAnalyzer!" << std::endl;
}

DECLARE_ANALYZER(MyAnalyzer);
```
**test.py**
```python
from LDMX.Framework import ldmxcfg
p = ldmxcfg.Process('myana')
p.maxEvents = 10
p.outputFiles = ['/dev/null']
p.sequence = [
    ldmxcfg.Analyzer.from_file('MyAnalyzer.cxx')
]
```
Then I can check the resulting running
```
tom@nixos:~/code/ldmx/1308-standalone-processor$ denv fire test.py 
---- LDMXSW: Loading configuration --------
Processor source file /home/tom/code/ldmx/1308-standalone-processor/MyAnalyzer.cxx is newer than its compiled library /home/tom/code/ldmx/1308-standalone-processor/libMyAnalyzer.so (or library does not exist), recompiling...
done compiling /home/tom/code/ldmx/1308-standalone-processor/MyAnalyzer.cxx
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
1 Hello from MyAnalyzer!
2 Hello from MyAnalyzer!
3 Hello from MyAnalyzer!
4 Hello from MyAnalyzer!
5 Hello from MyAnalyzer!
6 Hello from MyAnalyzer!
7 Hello from MyAnalyzer!
8 Hello from MyAnalyzer!
9 Hello from MyAnalyzer!
10 Hello from MyAnalyzer!
---- LDMXSW: Event processing complete  --------
tom@nixos:~/code/ldmx/1308-standalone-processor$ denv fire test.py 
---- LDMXSW: Loading configuration --------
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
1 Hello from MyAnalyzer!
2 Hello from MyAnalyzer!
3 Hello from MyAnalyzer!
4 Hello from MyAnalyzer!
5 Hello from MyAnalyzer!
6 Hello from MyAnalyzer!
7 Hello from MyAnalyzer!
8 Hello from MyAnalyzer!
9 Hello from MyAnalyzer!
10 Hello from MyAnalyzer!
---- LDMXSW: Event processing complete  --------
tom@nixos:~/code/ldmx/1308-standalone-processor$ sed -i 's/Hello/Goodbye/g' MyAnalyzer.cxx 
tom@nixos:~/code/ldmx/1308-standalone-processor$ denv fire test.py 
---- LDMXSW: Loading configuration --------
Processor source file /home/tom/code/ldmx/1308-standalone-processor/MyAnalyzer.cxx is newer than its compiled library /home/tom/code/ldmx/1308-standalone-processor/libMyAnalyzer.so (or library does not exist), recompiling...
done compiling /home/tom/code/ldmx/1308-standalone-processor/MyAnalyzer.cxx
---- LDMXSW: Configuration load complete  --------
---- LDMXSW: Starting event processing --------
1 Goodbye from MyAnalyzer!
2 Goodbye from MyAnalyzer!
3 Goodbye from MyAnalyzer!
4 Goodbye from MyAnalyzer!
5 Goodbye from MyAnalyzer!
6 Goodbye from MyAnalyzer!
7 Goodbye from MyAnalyzer!
8 Goodbye from MyAnalyzer!
9 Goodbye from MyAnalyzer!
10 Goodbye from MyAnalyzer!
---- LDMXSW: Event processing complete  --------
```

</details>

### CODE REVIEW

**Review by tvami — APPROVED** [review]
I ran this "DQM-style", i.e. took the pn config and added the MyAnalyzer with an extend and also took the `EcalVetoResult` object and printed out the `getDeepestLayerHit()`. All looks great! Thanks Tom for doing this!

<details>
  <summary>Here is the pn config with the `MyAnalyzer`</summary>

```
from LDMX.Framework import ldmxcfg
p = ldmxcfg.Process('test')

p.maxTriesPerEvent = 10000

from LDMX.Biasing import ecal
from LDMX.SimCore import generators as gen
det = 'ldmx-det-v14'
mySim = ecal.photo_nuclear(det,gen.single_4gev_e_upstream_tagger())
mySim.beamSpotSmear = [20.,80.,0.]
mySim.description = 'ECal PN Test Simulation'

p.sequence = [ mySim ]

##################################################################
# Below should be the same for all sim scenarios

import os
import sys

p.maxEvents = 10
p.run = 2

p.histogramFile = f'hist.root'
p.outputFiles = [f'events.root']
p.termLogLevel = 0

import LDMX.Ecal.EcalGeometry
import LDMX.Ecal.ecal_hardcoded_conditions
import LDMX.Hcal.HcalGeometry
import LDMX.Hcal.hcal_hardcoded_conditions
import LDMX.Ecal.digi as ecal_digi
import LDMX.Ecal.vetos as ecal_vetos
import LDMX.Hcal.digi as hcal_digi

from LDMX.TrigScint.trigScint import TrigScintDigiProducer
from LDMX.TrigScint.trigScint import TrigScintClusterProducer
from LDMX.TrigScint.trigScint import trigScintTrack
ts_digis = [
        TrigScintDigiProducer.pad1(),
        TrigScintDigiProducer.pad2(),
        TrigScintDigiProducer.pad3(),
        ]
for d in ts_digis :
    d.randomSeed = 1

from LDMX.Recon.electronCounter import ElectronCounter
from LDMX.Recon.simpleTrigger import TriggerProcessor

count = ElectronCounter(1,'ElectronCounter')
count.input_pass_name = ''

from LDMX.DQM import dqm

p.sequence.extend([
        ecal_digi.EcalDigiProducer(),
        ecal_digi.EcalRecProducer(), 
        ecal_vetos.EcalVetoProcessor(),
        hcal_digi.HcalDigiProducer(),
        hcal_digi.HcalRecProducer(),
        *ts_digis,
        TrigScintClusterProducer.pad1(),
        TrigScintClusterProducer.pad2(),
        TrigScintClusterProducer.pad3(),
        trigScintTrack, 
        count, TriggerProcessor('trigger', 4000.),
        dqm.PhotoNuclearDQM(verbose=True),
        ] + dqm.all_dqm)


p.sequence.extend([
    ldmxcfg.Analyzer.from_file('MyAnalyzer.cxx')
])
```
</details> 

<details>
  <summary>Here is the `MyAnalyzer` cxx file</summary>

```
// in MyAnalyzer.cxx
#include "Framework/EventProcessor.h"
// not used but want to make sure includes from other modules is working
#include "Ecal/Event/EcalHit.h"
#include "Ecal/Event/EcalVetoResult.h"

class MyAnalyzer : public framework::Analyzer {
 public:
  MyAnalyzer(const std::string& name, framework::Process& p)
    : framework::Analyzer(name, p) {}
  ~MyAnalyzer() = default;
  void analyze(const framework::Event& event) final;
};

void MyAnalyzer::analyze(const framework::Event& event) {
  auto veto{event.getObject<ldmx::EcalVetoResult>("EcalVeto","")};
  std::cout << event.getEventNumber() << " Hello from MyAnalyzer!" << std::endl;
  std::cout << "getDeepestLayerHit " << veto.getDeepestLayerHit() << std::endl;
}

DECLARE_ANALYZER(MyAnalyzer);
// in MyAnalyzer.cxx
#include "Framework/EventProcessor.h"
// not used but want to make sure includes from other modules is working
#include "Ecal/Event/EcalHit.h"
#include "Ecal/Event/EcalVetoResult.h"

class MyAnalyzer : public framework::Analyzer {
 public:
  MyAnalyzer(const std::string& name, framework::Process& p)
    : framework::Analyzer(name, p) {}
  ~MyAnalyzer() = default;
  void analyze(const framework::Event& event) final;
};

void MyAnalyzer::analyze(const framework::Event& event) {
  auto veto{event.getObject<ldmx::EcalVetoResult>("EcalVeto","")};
  std::cout << event.getEventNumber() << " Hello from MyAnalyzer!" << std::endl;
  std::cout << "getDeepestLayerHit " << veto.getDeepestLayerHit() << std::endl;
}

DECLARE_ANALYZER(MyAnalyzer);
```
</details>

**Comment by tvami** [comment]
@tomeichlersmith because of my PR to add the `totalEvents` that also touched `ldmxcfg.py.in` there is now a conflict to be resolved:
Screenshot 2024-05-07 at 08 50 04

**Comment by tomeichlersmith** [comment]
I was able to rebase cleanly to accomodate the changes introduced by #1322

```
git switch trunk
git pull
git switch 1309-1308-python-config-cleanup
git rebase trunk
# no conflicts :D
git push -f
```

**Review by bryngemark — COMMENTED** [review]
thanks @tomeichlersmith for doing some tedious maintenance besides introducing some really neat functionality. i have a feeling we might be opening the door here to some handy workflows but i admit i haven't thought about it at length. 

about the example cleanups, i'm all for them as they are, and i wonder, are there still/now any good examples for people to look at when they wonder how to run things? might those be the CI configs, and do they cover what most people need? should we move to using the same configs in CI tests and most sample production? 

i'm thinking that most analysis oriented development work goes along with a sample being produced and a few things tested in an analyzer. i kind of like the idea that this becomes a CI test sample + validation histogram suite, as a way to capture expertise once it's fresh and make sure it gets documented at least in code.

**Comment by tomeichlersmith** [comment]
> are there still/now any good examples for people to look at when they wonder how to run things?

I agree that the CI configs (`.github/validation_samples/*/config.py`) are some of the most complete examples and are routinely tested for functionality so that is where I point people towards first. I also want to plug the [documentation I've been writing](https://ldmx-software.github.io/config/intro.html). With our config system being a specialization of Python, I think it is feasible for everyone to focus on understanding how to write a config from scratch (obviously not immediately, but given some time).

> do they cover what most people need?

No - I think the CI does do a good job of testing the "standard" simulation samples, but the physical-realness (or even the functionality) of other example/test configs are not tested and so are not ensured. They still offer a starting point, but might not work out of the box.

> should we move to using the same configs in CI tests and most sample production?

I think this is a good goal. I think we're already pretty close, but I'm not sure how different the specific processor configurations are from one another.

**Comment by tomeichlersmith** [comment]
> analysis oriented development

I think this `from_file` function (along with `denv`) enables a specific workflow which I've started employing regularly. Most recently, I've wanted to re-reconstruct while varying the ECal calibrations to study systematics so that is the example I give below.

1. Oh I need to generate specific simulation (or several simulations varying some parameter or several reconstructions of the same simulation varying some parameter): I need to re-run `EcalRecProducer` while changing the `EcalRecConditions`
2. Pick a version of ldmx-sw that allows for the parameter(s) you want to change `denv init ldmx/pro:v3.3.6 ecal-conditions-systematics`
3. Write a single-file analyzer that makes the histograms you want `ecal-conditions-systematics/TriggerAnalyzer.cxx`
4. Write a config that does any preparatory work and then runs the analysis (in my case, I define the EcalRecConditions in the config with my criteria and then the processors are the ecal rec producer and my TriggerAnalyzer)
5. Look at the histograms in whatever method you see fit (I just JupyterLab+`hist` but others use ROOT browser)

The benefits of this workflow are
- Fixed version of ldmx-sw without needing to re-clone or re-compile
- Analysis in structure ready for integration into ldmx-sw (e.g. into DQM), could literally upload the analyzer file using GitHub on the browser

The downsides of this workflow are
- Most efficient path is three stages (`fire sim.py`, `fire ana.py`, look at histograms in some other tool for plotting): users could easily combine `sim.py` and `ana.py` but that means they'd be wasting time re-running the expensive upstream processors for any small analysis change.
- Analyzers need to write C++: while I want to encourage folks to contribute to ldmx-sw (and this is a good first step towards doing that), the unforgiving syntax of C++ is an obstacle that prevents people from focusing on the physics.

I outline a (efficient) python analysis workflow [on the docs](https://ldmx-software.github.io/analysis/python.html) that would resolve these downsides from my point of view. There is a clear separation between two stages (one is `fire config.py` which produces the ROOT file for analysis, the other inputs the ROOT file and analyzes the data) and analyzers would be using Python (with its more forgiving syntax) along with its plethora of support libraries (which are mostly well documented).

**Pull request merged**
