### PR TITLE
Generate an event from the scoring plane trajectories

### PR DESCRIPTION
**Pull request by nhanvtran**
.mac for testing in SimApplication/data/g4macros/generators/mu_gun*

There are 2 steps: 
step1, muon gun shoots through v3 geom with scoring planes
step2, find the muon exiting the back of the ecal scoring plane and regenerate that

This also fixes the bug (in `UserActionPlugin.cxx`) so that it always saves particles with gen status == 1.

### CODE REVIEW

**Comment by omar-moreno** [comment]
@nhanvtran Did you check that you get the same Hcal information back after you regenerate?

**Comment by nhanvtran** [comment]
ah darn, will try to do tonight

**Comment by omar-moreno** [comment]
Great, thanks!

**Comment by nhanvtran** [comment]
hi all finally did this check...no problems.  events are the same after regenerating, we're good to go here i think

**Comment by omar-moreno** [comment]
Alright, I'll merge it in.

**Pull request merged**
