### PR TITLE
Cleanup calorimeter geometry in v1 detector

### PR DESCRIPTION
**Pull request by awhitbeck**
- Cleaned up hcal geometry
- Decoupled wrap-around hcal from backing hcal
- Put ecal and hcal in separate parent geometries
- Put ECal in separate files
- Adding lots of configuration parameters to hcal geometry for optimization studies

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
Can you put back the field map in detectors.gdml?  It is currently commented out.

**Comment by JeremyMcCormick** [comment]
Also, you can take this out I believe as it does not appear to be used ...

```
<box lunit="mm" name="expHall_box0x2731e20" x="20000" y="20000" z="40000"/>
```

**Comment by JeremyMcCormick** [comment]
There is a conflict showing on this branch.  Can you merge in the master to your branch and resolve this before I approve the PR?  I think there were some minor changes to detector.gdml that were merged into master that you should incorporate.

**Comment by awhitbeck** [comment]
For the conflict, there was some white space that it complained about and then git, for some reason, complained about replacing the calorimeter physvol tags with the separate ecal and hcal physvol tags.  The only conflicts were in detector.gdml and you can see my resolution commit here:

https://github.com/awhitbeck/ldmx-sw/commit/8480bcf5312f5beaaf98d1d4852b2f1e50c27e35

Since there were no changes made to my branch, I don't think I can resolve this?

There are two other issues that we want to fix before we merge this though:

 - replace stainless steel with plain steel.  This was found to have a sizable difference in the performance and steel is what we were using for the "LOI".
 - add copy numbers to the wrap around hcal so that the detids are unique.

**Comment by JeremyMcCormick** [comment]
I'm going to make another PR from a branch off LDMXAnalysis/ldmx-sw.

**Pull request closed without merging**
