### PR TITLE
Iss444

### PR DESCRIPTION
**Pull request by bechenard**
New Hcal geom for v5 detector. I kept the side HCAL length to 290 mm instead of 300mm to avoid messing with the virtual detectors.

### CODE REVIEW

**Comment by awhitbeck** [comment]
I looked at the new geometry, it looks good to me.  I ran an overlap check and everything passed.  It does seem like the back scoring plane is a bit far from the last layer. See plot below.  If we are going to change the scintillator size, we might want to adjust this.  I have no strong feelings about the scintillator thickness, by the way.

image

Blue is sim hit z position, red is scoring plane hit z position

**Comment by bechenard** [comment]
HI Andrew,


It is true I never looked at the virtual detector. I don't think the gap 
is a big issue if the scoring plane is large enough, though.

Cheers,

Bertrand

**Comment by omar-moreno** [comment]
Also ran the overlap check and can confirm things look fine.  I think as long as the new hcal geometry falls inside of the scoring planes, it should be fine.  I can do a quick check of this.

**Comment by omar-moreno** [comment]
Looks like the Hcal falls inside of the Hcal scoring plane volumes (blue below)

image

image

**Comment by omar-moreno** [comment]
Zooming in a bit on the front face, it looks like the Ecal extends outside of the scoring plane volume now.  Actually, it looks like the whole Ecal/Hcal system got shifted forward a bit.  I need to check to make sure if there isn't overlap with the magnet.

**Comment by bechenard** [comment]
Hi Omar,


Yes, I also noticed that, hence my previous comment. I kept the geometry 
the same size as I wasn't sure if this would mess up with the 
re-simming. I believe the proper way to fix that is to get rid of the 
different offsets introduced (+1 for the ECAL bounding box, and a -2.5 
for the HCAL z position).

Let me know if this messes up with the re-simming - doing some work on 
that right now.

Cheers,

Bertrand

**Comment by omar-moreno** [comment]
@bechenard As long as the non-parallel world geometry has no overlaps (which at the moment it doesn't), resiming shouldn't be an issue. The Hcal can be whatever size it needs to be. 

I'm fixing the overlaps with the scoring planes now.  Those are easy fixes.

**Comment by omar-moreno** [comment]
Well, giving that we have no concrete answer as to what the Hcal size should be, sticking with a giant Hcal is the way to go.

**Comment by awhitbeck** [comment]
By the way, I thought the plan was that the strips allow the side hcal would go along the z-direction so that the fibers would come out the side instead of the front?

**Comment by bechenard** [comment]
The strips need to go along the x or y direction to come out of the 
sides. Along the z direction, you either end up in the magnet of the 
back HCAL. Or an I missing something?

**Comment by awhitbeck** [comment]
Sorry I meant segmented along z (which has a width of 29cm).  I think currently they are segmented along x and y.

**Comment by bechenard** [comment]
I need to check this. It could very well be that I didn't update the 
code when we decided to change the segmentation.

**Comment by omar-moreno** [comment]
This branch was merged into v4_hcal_dev and will be merged into master when that branch gets merged.  This PR is no longer necessary.

**Pull request closed without merging**
