### PR TITLE
Iss1102

### LINKED ISSUE #1102: TrigScint naming updates
**Describe the bug**
In the simulation module, the updated TrigScint geometry renamed the collections that it produced. This is a logical update which unfortunately has the cascading effect of requiring updates to the downstream input/output collection names.

In order to get the validation samples running, I commented out the TrigScint digi pipelines and the TrigScint DQM. This is obviously not long term, but I need someone more familiar with the TS pipeline to do the cascading name updates. Basically, I would like some updates allowing us to undo everything in https://github.com/LDMX-Software/ldmx-sw/commit/faad25ceaa5575a7b2c12ff587a3684190e84b16 .

@awhitbeck @bryngemark Maybe one of you has time this week to do this update?

### PR DESCRIPTION
**Pull request by awhitbeck**
Updates for new simulations for the DR doc.

### What are the issues that this addresses?
This resolves #1102.  

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] Check distributions of hits in the TS and target detectors: 

https://user-images.githubusercontent.com/4173436/197055627-676516c0-2ad7-43fe-94b8-f7a0454f4d1f.png
image
image
image

- [ ] To reproduce these results, minor changes are needed to SimCore to update the default beam configuration for firing electrons upstream of the TS modules: 

```
p.sequence[0].generators[0].position=[-44.,0.,-880.]
theta = math.radians(5.65)
p.sequence[0].generators[0].direction=[math.sin(theta),0.,math.cos(theta)]
p.sequence[0].generators[0].energy=4.
```

### Related Sub-Module PRs
- https://github.com/LDMX-Software/SimCore/pull/77
- https://github.com/LDMX-Software/TrigScint/pull/47

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
The SimCore updates have been made and the reference on trunk has been updated to the [new patch release v1.3.2](https://github.com/LDMX-Software/SimCore/releases/tag/v1.3.2). Rebasing this branch onto trunk (or merging trunk) will provide the necessary SimCore updates.

_Edit_: To be clear, the SimCore update _only_ has the primary generator update. In the process of renaming the different Trigger Pads, there will probably need to be more updates to SimCore.

**Comment by awhitbeck** [comment]
thanks, Tom. 

I'll merge trunk into this branch and run some basic tests. 

Agreed, we should change naming conventions.  Before merging?  @bryngemark : FYI

**Comment by bryngemark** [comment]
I say, let's keep the name changes in SimCore as part of that PR

**Comment by bryngemark** [comment]
I have renamed everything, and can verify that I am able to run digi out of the box after updating all the collection names in the configs. 

Thought I'd share the _x_ distribution after running 200 events with the normal beamspot size (20x80mm)  To me this answers @awhitbeck's question if it's tuned enough: I think so.


Most upstream:
pad1SimHit_x

Second pad, just upstream of the tagger:
pad2SimHit_x

Third pad, just upstream of the target
pad3SimHit_x

**Comment by tomeichlersmith** [comment]
## Pre-Merge To Do List
For anyone, I'm willing to do these things if everything else is done.
- [x] Make sure v12 can still run by updating TS SD configuration
- [x] Re-enable TS stuff in validation_samples
- [x] Merge TS SimCore updates, make another release, and bump reference here
- [x] Put TrigScint update on its trunk and bump reference here

**Comment by bryngemark** [comment]
> ## Pre-Merge To Do List
> For anyone, I'm willing to do these things if everything else is done.
> 
> * [ ]  Make sure v12 can still run by updating TS SD configuration
> * [ ]  Re-enable TS stuff in validation_samples
> * [ ]  Merge TS SimCore updates, make another release, and bump reference here
> * [ ]  Put TrigScint update on its trunk and bump reference here

I think everything else for this issue is done. If you have time @tomeichlersmith, please go ahead and wrap up these tasks.

**Comment by bryngemark** [comment]
I updated the name in the existing scoring plane to reflect the geometry name changes.

**Pull request merged**
