### PR TITLE
Scoring Planes and Parallel Worlds! 

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
Oh my....I won't have a chance to look at this until around July 25, unfortunately.  If you need it merged before then perhaps you will need to deploy your admin override or get someone else to look at it.  :)

**Comment by nhanvtran** [comment]
I can help with testing since I have to make this work with the particle generators...I can figure out how to invoke this by the Messenger class but it might be good to commit an example .mac

**Comment by omar-moreno** [comment]
@nhanvtran I committed an example macro.  I ran a few brief test yesterday and things seem to be working as expected.  I'll show some plots at the Monday software meeting.

**Comment by nhanvtran** [comment]
Hey @omar-moreno thanks.  I'm at a conference this week so it will be hit-or-miss.  I won't make the Monday Software meeting.  Do you mind putting what you show on Indico so I can look through them later?

**Comment by omar-moreno** [comment]
@nhanvtran Will do.

**Comment by omar-moreno** [comment]
@nhanvtran Going to close this since it's going to be merged as part of v3-dev.

**Pull request closed without merging**
