### PR TITLE
Merge MIP tracking changes

### PR DESCRIPTION
**Pull request by p-masterson**
This PR adds the updated MIP tracking algorithm to the ECal module, addressing issue 15.  The relevant changes are in EcalVetoProcessor.h/cxx and EcalVetoResult.h/cxx.

Currently, 0-2 straight tracks are required to pass the veto; this could be tweaked if necessary to improve signal efficiency.

Edit:  The corresponding Ecal PR is [here.](https://github.com/LDMX-Software/Ecal/pull/27)

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
@omar-moreno I've worked with @p-masterson to finish up the MIP stuff in ECal: https://github.com/LDMX-Software/Ecal/pull/27

This PR is ready, but the submodule refs are kinda funky. I think this has to do with the EaT PR hanging on SimCore: https://github.com/LDMX-Software/SimCore/pull/42

**Comment by omar-moreno** [comment]
> @omar-moreno I've worked with @p-masterson to finish up the MIP stuff in ECal: [LDMX-Software/Ecal#27](https://github.com/LDMX-Software/Ecal/pull/27)
> 
> This PR is ready, but the submodule refs are kinda funky. I think this has to do with the EaT PR hanging on SimCore: [LDMX-Software/SimCore#42](https://github.com/LDMX-Software/SimCore/pull/42)

OK, just to make sure, there were no changes made to SimCore?

**Comment by tomeichlersmith** [comment]
Correct, no changes in SimCore, just in Ecal.

**Comment by omar-moreno** [comment]
> Correct, no changes in SimCore, just in Ecal.

Yeah, just merged in trunk and diff is better. 

After improving comments a bit, I'm fine with this getting merged in.

**Review by omar-moreno — APPROVED** [review]

**Review by tomeichlersmith — APPROVED** [review]
@omar-moreno We are good to go!

**Pull request merged**
