### PR TITLE
Skimming support for ldmx-app

### PR DESCRIPTION
**Pull request by jmmans**
This PR resolves issue #254 , allowing any event processor to indicate that a given event should be kept or dropped.  The user can specify in the python file which event processors are to listened to, and the framework will keep only the specified set of events in the output file.

### CODE REVIEW

**Comment by nhanvtran** [comment]
Going through this now @jmmans 
It would be nice to add a few examples to this PR.  
I'm not sure if they should go in `EventProc/python` or `Configuration/python` -- @JeremyMcCormick   @omar-moreno what's the agreed convention here?  

Based on a first reading, I guess it's some examples of `p.skimRules = []`.  I'm testing it now and can put some examples in myself, but @jmmans guidance would be welcome.

**Comment by omar-moreno** [comment]
I would say put them in EventProc/python.

**Comment by JeremyMcCormick** [comment]
Full example configs should go in Configuration/python .

The EventProc/python scripts contain classes to be instantiated, not actual
runnable examples.

**Comment by jmmans** [comment]
Added a sample python file, ready for merge!

**Comment by nhanvtran** [comment]
Did a functionality test, looks good.  I'd say this is ready to merge.  However, @jmmans, it would also be nice to add some documentation on a bunch of different skim rules -- not obvious to the user all the possible options...

**Comment by JeremyMcCormick** [comment]
@jmmans The indentation level in the code you've changed is mostly just wrong, and there are tabs in it as well.  I will fix it this time, but please in the future use spaces only and match the existing indentation.  (There's a bunch of methods you've added here whose indentation doesn't even line up with the existing ones.)

**Comment by jmmans** [comment]
@JeremyMcCormick : I would certainly appreciate a working solution to meet the tabbing requirements.  I have tried a few things in emacs to acheive this, but they have all been a failure -- that how the tabs are appearing.

Jeremy

**Comment by JeremyMcCormick** [comment]
You can put this into your `.emacs` file:

```
(setq-default indent-tabs-mode nil)
```

And set the tab width using the variable:

```
tab-width
```  

If worse comes to worse, then hit the spacebar instead of the tab key.  :-)

**Comment by JeremyMcCormick** [comment]
The indentation should be fixed now and I exterminated all the tabs.

@nhanvtran  and I were wondering if there could be more complex examples added as the sample one seems to only test the most basic functionality (dropping/keeping via modulus rule).

For instance, I assume you tested the mechanism of the drop/keep consensus amongst processors through their "votes" but we don't have a good way to test this or other more complex rules to know that it actually works.  Probably that should all be tested before this is merged.

**Comment by jmmans** [comment]
I've tested the basic support of allowing "any" to keep or reject.  The other code is there to build on for the future.  We need this for operations purposes!

**Pull request merged**
