### PR TITLE
Iss643 dev - Boost logging. 

### PR DESCRIPTION
**Pull request by omar-moreno**
This cherry picks the minimal changes pushed into iss643.  That branch is really outdated and still needs some work so it's best to start clean.

### CODE REVIEW

**Comment by omar-moreno** [comment]
@tomeichlersmith Let's finish up putting in the necessary logging classes without changing all processors to make use of the logging.

**Comment by tomeichlersmith** [comment]
Is there a reason you remved the `enableLogging` and `ldmx_log` macros at the end of `Logger.h`?

**Comment by omar-moreno** [comment]
It's likely that they weren't cherry picked.  Let me check.

**Comment by tomeichlersmith** [comment]
The other thing that I noticed is that you copied over no changes to the application source file. (formerly ldmx_app.cxx). This setup is necessary for logging to function anywhere in ldmx-sw, but I could see delaying those changes for a later PR where we actually implement the cleanup of logging in most/all of ldmx-sw.

**Comment by omar-moreno** [comment]
I had a question related to that.  Why not setup the configuration from the
python config?

**Comment by tomeichlersmith** [comment]
I wanted to be able to have all exceptions to be included in the logging. Since we have some exceptions in the `ConfigurePython` class, it needed to be separate.

If we are okay, with the `ConfigurePython` having exceptions _not_ included in the logging, then we could definitely have the logging configured in the python.

**Comment by omar-moreno** [comment]
I think that's fine.

**Comment by tomeichlersmith** [comment]
Ok, I think that is complicated enough, we should put it on a different issue and I can implement that over the next few weeks.

**Pull request merged**
