### PR TITLE
Hcal and ts bug/performance patches

### PR DESCRIPTION
**Pull request by EinarElen**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
_Hint_: Use the phrase '_This resolves #< issue number >_' so that they are linked automatically.
This resolves 
- https://github.com/LDMX-Software/Hcal/issues/18 
- https://github.com/LDMX-Software/Hcal/issues/58
- https://github.com/LDMX-Software/Hcal/issues/66
- https://github.com/LDMX-Software/Hcal/issues/67 
- https://github.com/LDMX-Software/TrigScint/issues/53 

While doing this it also contributes to resolving 
- #1176  
- #1168  
- #1166 
- #1208 (See in particular the non-void functions not returning) 

With this PR merged LDMX-sw mostly[^1] compiles with both GCC and Clang. This doesn't mean that LDMX-sw runs when compiled by clang, but we could consider integrating a build by clang into CI for better coverage of static issues (and sometimes, better feedback)  

[^1] There are some warnings that Clang (correctly) treats as errors that GCC lets by. These can be disabled if you need to compile ldmx-sw with clang. 
## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments

- [x] I ran my developments and the following shows that they are successful.

Been using these changes in development for a while now, they run without issue. Validation results will be nice to confirm with

- [x] I attached any sub-module related changes to this PR.

_Explanation_: You need to specifically `git add` your submodule's commit in _ldmx-sw_ and then have a separate PR within that submodule.
```
# outline of submodule commit updating
cd SUBMODULE
git checkout updates
cd ..
git add SUBMODULE
git commit -m "I updated the commit for SUBMODULE to the last commit of my-updates"
```
- Bump HCal to [v0.3.5](https://github.com/LDMX-Software/Hcal/releases/tag/v0.3.5 
- Bump TS to cb60589597edea854031594e25ead4a37fc1c829 
### Related Sub-Module PRs
If you have developments in a submodule that you need to merge in along with these developments, please link those PRs here, otherwise just delete this section.
_Note_: You do not need to make a Sub-Module PR if your submodule developments are already on that repo's default branch.

- https://github.com/LDMX-Software/Hcal/pull/70
- https://github.com/LDMX-Software/TrigScint/pull/54

### CODE REVIEW

**Comment by EinarElen** [comment]
Ummm.... what on earth does that failure mean?

**Comment by EinarElen** [comment]
Ok looks like the first failure was just a fluke/something going wrong on the GH side of things. 

The failing plot is the following, which is odd. This was the figure that was updated in https://github.com/LDMX-Software/ldmx-sw/pull/1219 
HcalInefficiencyAnalyzer_HcalInefficiencyAnalyzer_efficiency

I will run some cross-checks to see what's going on here

**Comment by EinarElen** [comment]
I can't reproduce the failing figures locally. I tried compiling ldmx-sw from origin/trunk, running the EcalPN config and then repeating the process with the version from the PR (submodules checked out correctly). 
HcalInefficiencyAnalyzer_efficiency png-1

I also checked and all the other histograms are identical. @tomeichlersmith do you have any idea what might have happened here?

**Comment by tomeichlersmith** [comment]
The reason the PR Validations are failing here (and not locally) is because that run started _before_ I merged in the updated golden histograms #1221 and so they are actually comparing against v3.3.1 gold instead of v3.3.2. I am willing to bet they will pass if we Convert to draft and then Ready for Review this PR.

**Comment by EinarElen** [comment]
Right, that makes sense. I'm re-running them now

**Comment by EinarElen** [comment]
All the PR validation runs passed on the second attempt :)

**Review by tomeichlersmith — APPROVED** [review]
Looks good :+1:

**Pull request merged**
