### PR TITLE
Change tracking timing precision, fixes to DQM histo names

### LINKED ISSUE #1402: Tracking timing changes in log diffs
**Is your feature request related to a problem? Please describe.**
Logs always fail now because of the character count different
```
<  [ SeedFinderProcessor ] 1 : AVG Time/Event: 0.0986296 ms
  ---
  >  [ SeedFinderProcessor ] 1 : AVG Time/Event: 0.0978154 ms
  244c244
  <  [ SeedRecoil ] 1 : AVG Time/Event: 0.136037 ms
  ---
  >  [ SeedRecoil ] 1 : AVG Time/Event: 0.133573 ms
  256c256
  <  [ Tagger_TrackFinder ] 1 : AVG Time/Event: 0.395085 ms
  ---
  >  [ Tagger_TrackFinder ] 1 : AVG Time/Event: 0.39516 ms
  258,263c258,263
  <  [ Tagger_TrackFinder ] 1 : setup       Avg Time/Event = 0.00228943 ms
  <  [ Tagger_TrackFinder ] 1 : hits        Avg Time/Event = 0.0433836 ms
  <  [ Tagger_TrackFinder ] 1 : seeds       Avg Time/Event = 0.00342895 ms
  <  [ Tagger_TrackFinder ] 1 : cf_setup    Avg Time/Event = 0.00407709 ms
  <  [ Tagger_TrackFinder ] 1 : ckf_run     Avg Time/Event = 0.000160371 ms
  <  [ Tagger_TrackFinder ] 1 : result_loop Avg Time/Event = 0.339842 ms
  ---
  >  [ Tagger_TrackFinder ] 1 : setup       Avg Time/Event = 0.00216297 ms
  >  [ Tagger_TrackFinder ] 1 : hits        Avg Time/Event = 0.044[55](https://github.com/LDMX-Software/ldmx-sw/actions/runs/10496314488/job/29077738861?pr=1401#step:6:58)07 ms
  >  [ Tagger_TrackFinder ] 1 : seeds       Avg Time/Event = 0.00345044 ms
  >  [ Tagger_TrackFinder ] 1 : cf_setup    Avg Time/Event = 0.00419966 ms
  >  [ Tagger_TrackFinder ] 1 : ckf_run     Avg Time/Event = 0.0001725 ms
  >  [ Tagger_TrackFinder ] 1 : result_loop Avg Time/Event = 0.33878 ms
  265c265
  <  [ Recoil_TrackFinder ] 1 : AVG Time/Event: 0.298821 ms
  ---
  >  [ Recoil_TrackFinder ] 1 : AVG Time/Event: 0.308164 ms
  267,272c267,272
  <  [ Recoil_TrackFinder ] 1 : setup       Avg Time/Event = 0.000543621 ms
  <  [ Recoil_TrackFinder ] 1 : hits        Avg Time/Event = 0.042665 ms
  <  [ Recoil_TrackFinder ] 1 : seeds       Avg Time/Event = 0.00260774 ms
  <  [ Recoil_TrackFinder ] 1 : cf_setup    Avg Time/Event = 0.00199831 ms
  <  [ Recoil_TrackFinder ] 1 : ckf_run     Avg Time/Event = 0.000136034 ms
  <  [ Recoil_TrackFinder ] 1 : result_loop Avg Time/Event = 0.250555 ms
  ---
  >  [ Recoil_TrackFinder ] 1 : setup       Avg Time/Event = 0.000690733 ms
  >  [ Recoil_TrackFinder ] 1 : hits        Avg Time/Event = 0.0449752 ms
  >  [ Recoil_TrackFinder ] 1 : seeds       Avg Time/Event = 0.00296358 ms
  >  [ Recoil_TrackFinder ] 1 : cf_setup    Avg Time/Event = 0.00209514 ms
  >  [ Recoil_TrackFinder ] 1 : ckf_run     Avg Time/Event = 0.000153931 ms
  >  [ Recoil_TrackFinder ] 1 : result_loop Avg Time/Event = 0.2[56](https://github.com/LDMX-Software/ldmx-sw/actions/runs/10496314488/job/29077738861?pr=1401#step:6:59)973 ms
```

**Describe the solution you'd like**

We should round these numbers to a fixed number of digits.
But also it's interesting that rerunning ACTS on the same events takes different times.

**Describe alternatives you've considered**

Figure out why those numbers are different, is that expected @bloodyyugo 

**Additional context**

PR test here https://github.com/LDMX-Software/ldmx-sw/actions/runs/10496314488/job/29077738861?pr=1401

### PR DESCRIPTION
**Pull request by tvami**
I am updating _ldmx-sw_, here are the details.

### What are the issues that this addresses?
Resolves https://github.com/LDMX-Software/ldmx-sw/issues/1402

## Check List
- [x] I successfully compiled _ldmx-sw_ with my developments
- [x] I ran my developments and the following shows that they are successful.

### CODE REVIEW

**Review by tomeichlersmith — COMMENTED** [review]
I think this looks good, the reason I'm holding approval is just because this changes the gold in two ways (in the logs and by adding the chi2/ndf histogram to the list of histograms that the current validation comparison tool can handle). Is there anything else we want to merge before changing the gold?

**Comment by tvami** [comment]
My take is that we can merge this, but not yet make a new patch release / gold. The changes introduced in this PR are exactly taking care of the things that don't work in the comparison, i.e. every validation now fails with (1) not finding the <stuff>/ndf plots and (2) due to the instability of the tracking timing measurement. By merging this every validation will continuingly fail at these two points, but for a different reason. i.e. it's like a status que until we cut new gold (for which that I agree that it's too early)

**Review by tomeichlersmith — APPROVED** [review]
I am convinced by your reasoning :+1:

**Comment by tvami** [comment]
I pushed one more cosmetics change in https://github.com/LDMX-Software/ldmx-sw/pull/1448/commits/4af0355d22d606b5ab3d35899d35a6e6255a7ec7
I thought this was not worth another issue / PR

**Comment by tvami** [comment]
@bloodyyugo are you ok with me changing the tracking DQM histo names? I think this is the only way to have the CI script understand that it's not a directory.

**Review by bloodyyugo — APPROVED** [review]
These all look fine to me.

**Comment by bloodyyugo** [comment]
Yeah, I was going to change this but you got to it first.  Thanks

> @bloodyyugo are you ok with me changing the tracking DQM histo names? I think this is the only way to have the CI script understand that it's not a directory.

**Pull request merged**
