### PR TITLE
Add HcalVetoProcessor.

### PR DESCRIPTION
**Pull request by omar-moreno**

### CODE REVIEW

**Comment by awhitbeck** [comment]
I know you're probably trying to just get this in, but probably we should make the cut value configurable.

**Comment by JeremyMcCormick** [comment]
I ran ldmx-app using `hcalVeto = ldmxcfg.Producer("hcalVeto", "ldmx::HcalVetoProcessor")` and it ran fine.  The veto doesn't pass most of the time (which I assume is expected).

We should make the number of PE a configurable parameter.  Then I think this can be merged.

**Comment by omar-moreno** [comment]
What kind of events did you process?  It's strange that the veto doesn't
pass ``most of the time''.

**Comment by JeremyMcCormick** [comment]
Most events do not have any activity in the HCal so you would expect all those to fail the veto.

**Comment by omar-moreno** [comment]
pass the veto.

On Wed, Mar 15, 2017 at 11:46 AM, Jeremy McCormick <notifications@github.com

**Comment by JeremyMcCormick** [comment]
Oh right, I had that flipped around....could just have been the events I was running (I think they were biased PN events).

**Comment by omar-moreno** [comment]
@awhitbeck Hcal veto is now configurable.  @JeremyMcCormick This is ready to be merged.

**Pull request merged**
