### PR TITLE
Enabling EaT 3rd Try

### LINKED ISSUE #800: Partial Energy Sort during Simulation Processing
**Is your feature request related to a problem? Please describe.**
The default method of stacking during the Geant4 simulation is setup so that the particles are
processed in reverse creation-order. This means that the primary particle is simulated all the way to zero KE and then the last particle it produced is simulated, etc. until the stack is emptied.

**Describe the solution you'd like**
A stacking strategy that partial sorts the particles by energy while they are being simulated would be the premier solution. This would allow us to make sure all the high energy particles are processed first, thus, making some filters _a lot_ more effiecient.

A basic first-order particle sort would make sure all particles above a certain energy threshold would be simulated before any particles below that threshold. This would also mean that particles that lose energy and go below the threshold are then suspended and aren't resumed until the other high-energy particles are dealt with.

This sorting method would be a `UserAction` that will need access to several different types: `STACKING`, `STEPPING`, and `TRACKING` I think are what's necessary.

**Describe alternatives you've considered**
One alternative is to force the particles to simulate in generation-order: primary, all primary's children, all primary's children's children, etc. This doesn't work as well becuase there are a lot of low energy particles that are produced that the simulation is wasting time on in the beginning.

**Additional context**
I got interested in developing this while researching ways to improve the efficiency of the ECal as Target simulation. This is intimately related to the mid-shower PN simulation as well.

### LINKED ISSUE #870: Dark Brem Filter Re-Design
I've been working on improving the UserActions that filter for different types of events used in the ECal as Target (EaT) project.

I am currently in the process of validating these filters for use with dark brems occurring in both the target and the ECal, so I wanted to bring that work into the official sphere.

This development will also include other filters that will be helpful for EaT including
- PrimaryToEcalFilter: Make sure the primary electron reaches the ecal with a certain energy
- EcalBremFilter: Make sure primary electron brems a photon of a minimum energy in the ECal
- EcalENFilter: Make sure primary electron loses at least a certain amount of energy to EN interactions in the ECal

## Still TODO
- [ ] Validate that the filters work for both the target and the ECal cases
- [x] Include and document target and ECal dark brem templates (like PN templates)
- [ ] Get [dependent changes to SimCore](https://github.com/LDMX-Software/SimCore/issues/20) validated and merged in

### PR DESCRIPTION
**Pull request by tomeichlersmith**
## Related Submodule PR
- https://github.com/LDMX-Software/SimCore/pull/42

## Summary of Changes
- Since `SimCore` calculates the weight from multiplying all the step weights together, no more biasing user actions should set the event wegith.
- Use the helper function `getEventInfo()` to get the pointer to the event info in user actions.
- Add Ecal and Target dark brem filters
- Add a biasing submodule `Utility` that is separately compiled.
- Add a Partial energy sorter for processing higher energy particles first
- Add filter for mid-shower nuclear (EN/PN) interactions in the ecal
- Add general github action that builds production image for a branch. If a destination DockerHub repo is defined, it will be pushed to it.
- Run github action tests on all branches and version tags

### CODE REVIEW

**Comment by omar-moreno** [comment]
@tomeichlersmith Given that you changed EcalProcessFilter, did you ever generate ECal PN events and compare to the existing sample?  Can you post the comparisons here?

**Comment by tomeichlersmith** [comment]
I'd be happy to do a more detailed study if you would like. The only change I've made (besides add several debugging comments when I was searching once upon a time) was remove the setting of the event weight. I validated that the weights don't change when using the new weight calculation within SimCore; although, I do not have plots of that saved.

**Comment by tomeichlersmith** [comment]
I've looked into this a little bit more over the weekend, and there are three changes on this branch that cause different behavior in the ECal PN simulation pipeline.

1. Output configuration of primary generator into RunHeader
    - This is just a simple typo-fix. On trunk, users will get the warning that the primary generator's configuration will not be saved to the RunHeader. On this branch, it will.
2. Save PN and EN energy totals in EventHeader
    - Pretty self-explanatory. Just changes the data file so that we can't do an easy comparison like a check sum.
3. Bias entire target region instead of "just" the target itself.
    - This is the only change that (unverified hypothesis) actually changes the physics output of the ecal pn pipeline. The TrigScint adds 0.02X0 to the target region, so this slightly increases the rate of ECal PN events (more material for the primary electron to hard brem in). I believe this is desirable? But, it opens the door to requiring a more detailed validation.

**Comment by omar-moreno** [comment]
> I've looked into this a little bit more over the weekend, and there are three changes on this branch that cause different behavior in the ECal PN simulation pipeline.
> 
> 1. Output configuration of primary generator into RunHeader
>    
>    * This is just a simple typo-fix. On trunk, users will get the warning that the primary generator's configuration will not be saved to the RunHeader. On this branch, it will.
> 2. Save PN and EN energy totals in EventHeader
>    
>    * Pretty self-explanatory. Just changes the data file so that we can't do an easy comparison like a check sum.
> 3. Bias entire target region instead of "just" the target itself.
>    
>    * This is the only change that (unverified hypothesis) actually changes the physics output of the ecal pn pipeline. The TrigScint adds 0.02X0 to the target region, so this slightly increases the rate of ECal PN events (more material for the primary electron to hard brem in). I believe this is desirable? But, it opens the door to requiring a more detailed validation.

This is desirable behavior but was left out intentionally because 1) With a biasing factor of 450, the rate increase was negligible 2) We wanted event generation to remain similar to what we had before so we could continue generating a larger sample going forward.  I would make biasing of the scintillators optional for now so we are able to reproduce old samples if necessary.

**Comment by tomeichlersmith** [comment]
Ok, I've updated the attaching functionality in [DetectorConstruction](https://github.com/LDMX-Software/SimCore/pull/42/files#diff-f81c3db0de43c16f4daa9c6a6912de7051554b803b08cfb4c1205bb3e79d3da2) so that we can separate the "old" method of attaching biasing operators where the "target" refers to only the tungsten target layer (and not the target region) and the "old_ecal" regers to only the tungsten and silicon layers in the ecal.

Now there are five options for attaching operators.
1. `target` - just the logical volume called `target`
2. `target_region` - any logical volume inside the region called `target`
3. `old_ecal` - tungsten or silicon logical volumes inside the ecal
4. `ecal` - tungsten, silicon, glue (CFMix), PCB, or aluminum volumes inside the ecal
5. Any other requested volume string will simply attach operators to any logical volumes with names that contain the passed string.

## Validation
I need to work through more of the differences because comparing the two outputs of the the configuration script below across the two branches does not produce the exact same output.
```python
from LDMX.Framework import ldmxcfg
from LDMX.Biasing import ecal
from LDMX.SimCore import generators
p=ldmxcfg.Process("ecalpn")
ecal_pn = ecal.photo_nuclear('ldmx-det-v12', generators.single_4gev_e_upstream_tagger())
import LDMX.Ecal.EcalGeometry
p.sequence=[ecal_pn]
p.outputFiles=['ecal_pn.root']
p.maxEvents = 100000
```

**Comment by tomeichlersmith** [comment]
Got it! The current PN biasing operator only biases direct children of the primary electron. I've added another configuration variable for that operator that allows the standard analysis to only bias direct children while the EaT analysis can bias any photon above the energy threshold.

## Validation
I ran the follow config file for both `trunk` and this branch (called `eat` here just for ease).
```python
from LDMX.Framework import ldmxcfg
from LDMX.Biasing import ecal
from LDMX.SimCore import generators
p=ldmxcfg.Process("ecalpn")
ecal_pn = ecal.photo_nuclear('ldmx-det-v12', generators.single_4gev_e_upstream_tagger())
import LDMX.Ecal.EcalGeometry
p.sequence=[ecal_pn]
p.outputFiles=['ecal_pn.root']
p.maxEvents = 100000
```
Then I compared the two files using the python script copied below.
[Here is the pdf-unification of the plots output by this script.](https://github.com/LDMX-Software/ldmx-sw/files/5953778/comp.pdf)
 This shows that the two branches produce identical results.

**Notes**
- I can't do a simple check-sum because of the changes to Run and Event Header between the two branches.
- I can't compare the SimParticle map without using a C++ analyzer (I don't know why this is??), so @omar-moreno let me know if you think this is necessary and I will dig into using the DQM PN analyzer and a larger sample.

### Comparison Python Script
```python
import ROOT, os

def get_event_tree(branch) :
    rf = ROOT.TFile.Open(f'{branch}/ecal_pn.root')
    t  = rf.Get('LDMX_Events')
    return rf, t

def get_hist(tree, branch, tree_name, color, fill) :
    tree.Draw(f'{branch}>>h_{tree_name}_{branch}')
    h = ROOT.gDirectory.Get(f'h_{tree_name}_{branch}')
    h.SetTitle(f'{tree_name};{branch}')
    h.SetLineColor(color)
    h.SetLineWidth(2)
    h.SetMarkerColor(color)
    if fill :
        h.SetFillColor(color)
    return h

trunk_f, trunk = get_event_tree('trunk')
eat_f  , eat   = get_event_tree('eat')
c = ROOT.TCanvas()
os.system('mkdir -p comp')

ROOT.gROOT.SetBatch(1)
ROOT.gStyle.SetOptStat(0)

def comp(br) :

    h_trunk = get_hist(trunk, br, 'trunk', ROOT.kBlue, True )
    h_eat   = get_hist(eat  , br, 'eat'  , ROOT.kRed , False)

    h_trunk.Draw()
    h_eat.Draw('same')

    c.BuildLegend()
    c.SaveAs(f'comp/{br}.pdf')

branches = [
        'EventHeader.eventNumber_',
        'EcalSimHits_ecalpn.edep_',
        'EcalSimHits_ecalpn.id_',
        'EcalSimHits_ecalpn.x_',
        'EcalSimHits_ecalpn.y_',
        'EcalSimHits_ecalpn.z_',
        'EcalSimHits_ecalpn.time_',
        'HcalSimHits_ecalpn.edep_',
        'HcalSimHits_ecalpn.id_',
        'HcalSimHits_ecalpn.x_',
        'HcalSimHits_ecalpn.y_',
        'HcalSimHits_ecalpn.z_',
        'HcalSimHits_ecalpn.time_',
        ]

for b in branches :
    comp(b)
```

**Comment by tomeichlersmith** [comment]
@omar-moreno Loading the event library into PyROOT allowed me to compare the SimParticle branch. [Everything is still lined up identically with the only changes being in the Event and Run Headers.](https://github.com/LDMX-Software/ldmx-sw/files/5974385/comp.pdf)

### Updated Comparison Python Script
```python

import ROOT, os

def load_lib(l) :
    ROOT.gSystem.Load(f'lib{l}.so')

load_lib('Framework')
for event_lib in ['SimCore','Ecal','Hcal'] :
    load_lib(f'{event_lib}_Event')

def get_event_tree(branch) :
    rf = ROOT.TFile.Open(f'{branch}/ecal_pn.root')
    t  = rf.Get('LDMX_Events')
    return rf, t

def get_hist(tree, branch, tree_name, color, fill) :
    tree.Draw(f'{branch}>>h_{tree_name}_{branch}')
    h = ROOT.gDirectory.Get(f'h_{tree_name}_{branch}')
    h.SetTitle(f'{tree_name};{branch}')
    h.SetLineColor(color)
    h.SetLineWidth(2)
    h.SetMarkerColor(color)
    if fill :
        h.SetFillColor(color)
    return h

trunk_f, trunk = get_event_tree('trunk')
eat_f  , eat   = get_event_tree('eat')
c = ROOT.TCanvas()
c.SetLogy()
os.system('mkdir -p comp')

ROOT.gROOT.SetBatch(1)
ROOT.gStyle.SetOptStat(0)

def comp(br) :

    h_trunk = get_hist(trunk, br, 'trunk', ROOT.kBlue, True )
    h_eat   = get_hist(eat  , br, 'eat'  , ROOT.kRed , False)

    h_trunk.Draw()
    h_eat.Draw('same')

    c.BuildLegend()
    c.SaveAs(f'comp/{br}.pdf')

branches = [ 
        'EventHeader.eventNumber_', 
        'EventHeader.weight_',
        'EcalSimHits_ecalpn.edep_', 
        'EcalSimHits_ecalpn.id_', 
        'EcalSimHits_ecalpn.x_', 
        'EcalSimHits_ecalpn.y_', 
        'EcalSimHits_ecalpn.z_', 
        'EcalSimHits_ecalpn.time_', 
        'HcalSimHits_ecalpn.edep_', 
        'HcalSimHits_ecalpn.id_', 
        'HcalSimHits_ecalpn.x_', 
        'HcalSimHits_ecalpn.y_', 
        'HcalSimHits_ecalpn.z_', 
        'HcalSimHits_ecalpn.time_', 
        'SimParticles_ecalpn.first',
        'SimParticles_ecalpn.second.time_',
        'SimParticles_ecalpn.second.x_',
        'SimParticles_ecalpn.second.y_',
        'SimParticles_ecalpn.second.z_',
        'SimParticles_ecalpn.second.energy_',
        'SimParticles_ecalpn.second.px_',
        'SimParticles_ecalpn.second.py_',
        'SimParticles_ecalpn.second.pz_',
        'SimParticles_ecalpn.second.endX_',
        'SimParticles_ecalpn.second.endY_',
        'SimParticles_ecalpn.second.endZ_',
        'SimParticles_ecalpn.second.endpx_',
        'SimParticles_ecalpn.second.endpy_',
        'SimParticles_ecalpn.second.endpz_',
        'SimParticles_ecalpn.second.mass_',
        'SimParticles_ecalpn.second.charge_',
        'SimParticles_ecalpn.second.daughters_',
        'SimParticles_ecalpn.second.parents_',
        'SimParticles_ecalpn.second.processType_',
        'SimParticles_ecalpn.second.pdgID_',
        ]

for b in branches :
    comp(b)
```

**Comment by omar-moreno** [comment]
OK, I think it's ready to merge. Let me take one final look.

**Comment by omar-moreno** [comment]
Once you address the couple of issues on the SimCore branch, I'll hit the
merge button.

**Pull request merged**
