### PR TITLE
Add detector data service

### PR DESCRIPTION
**Pull request by JeremyMcCormick**
- Adds detector data service that loads information from a detector GDML file into a DetectorElement hierarchy.

- Changed some names in the current detector GDML file to make them more friendly.

- Generated detector_full.gdml for the 'ldmx-det-full-v1-fieldmap' detector.

- Fixed name of 'ldmx-det-full-v1-fieldmap' in GDML file which was incorrect in the run header.

- Added DetectorElement implementations for all subsystems (ECal, Tagger, etc.).

- Added test `DetectorDataService_test.cxx` which loads detector and prints out detailed information.

- Added hook in event processing to callback EventProcessor objects when new detector data is loaded.

- Assigns ID values to all DetectorElement components (except HCal stations for now).

There will probably be some conflicts with other open PRs.  Probably it will be best to leave this merge for last, and conflicts can be fixed up on the branch before merging it in.

### CODE REVIEW

**Comment by JeremyMcCormick** [comment]
This merge will be delayed until after the March workshop.  Closing for now.

**Comment by JeremyMcCormick** [comment]
Closing for now as this needs some additional work before merging.

**Comment by omar-moreno** [comment]
Is it possible to break up all of this functionality? This is going to be a nightmare to review.  Furthermore, in it's current state, this is not something that I will feel comfortable merging in.  If not, this might need to wait for a while.

**Comment by omar-moreno** [comment]
Also, if you are planning on loading the detector using TGeoManager, it will have issues with tessellated volumes: 

https://savannah.web.cern.ch/savannah/HEP_Applications/savroot/bugs/96282.html

So we will need a geometry for the sim and for recon.  This isn't ideal so looking for a way around this is going to be a priority.

**Comment by JeremyMcCormick** [comment]
Sorry if this was unclear but I didn't mean for this to be aporoved in its current state.  I'm going to close this for now and we can discuss everything you mentioned when I actually want to merge.

**Pull request closed without merging**
