### PR TITLE
extraction again, this time with workflows

### PR DESCRIPTION
**Pull request by tomeichlersmith**
We just wanted to be careful and make sure the history was preserved as best as possible.

### CODE REVIEW

**Comment by tomeichlersmith** [comment]
@omar-moreno Maybe I'm just getting cold feet, but we could hold off on this extraction until v2.1 release or some other larger milestone. I could work on getting ldmx-analysis pulled in as a submodule and that can be our experimental ground.

**Comment by omar-moreno** [comment]
I think it's fine if we do it now. I'm actively testing this and it seems
to be working fine.

**Comment by tomeichlersmith** [comment]
The biggest issue I'm running into is I can't figure out a way to pull down the submodules inside of the GitHub action. I think it is important to keep the GitHub action so that we can have the building and testing be automatic, but I haven't been able to figure out how to get the submodules to be cloned correctly.

**Comment by omar-moreno** [comment]
We can switch to Travis if that's a big issue.

**Comment by tomeichlersmith** [comment]
Ok, sounds good to me

**Comment by omar-moreno** [comment]
This will be done in a different PR.

**Pull request closed without merging**
